apiVersion: v1
kind: Pod
metadata:
  name: test1-pod
spec:
  containers:
  - name: test1
    image: nginx
    ports:
    - containerPorts: 80
  - name: test2
    image: ubuntu
    command: ["sleep"]
    arg: ["3600"]